# Generated by Django 2.0.3 on 2018-03-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('party', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('educational_details', models.TextField(blank=True, null=True)),
                ('assets', models.CharField(blank=True, max_length=30, null=True)),
                ('liabilities', models.CharField(blank=True, max_length=30, null=True)),
                ('criminal_cases', models.TextField(blank=True, null=True)),
                ('election_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Constituencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=10)),
                ('upcoming_election_date', models.DateField()),
                ('upcoming_election_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Constituencies'),
        ),
    ]
