# Generated by Django 2.0.3 on 2018-03-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='pincode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='info.Constituencies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidates',
            name='constituency',
            field=models.CharField(max_length=30),
        ),
    ]
