# Generated by Django 2.0.3 on 2018-03-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180401_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencies',
            name='id',
        ),
        migrations.AlterField(
            model_name='constituencies',
            name='pincode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
