# Generated by Django 2.0.3 on 2018-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180401_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencies',
            name='state',
            field=models.CharField(default='West Bengal', max_length=30),
            preserve_default=False,
        ),
    ]
